// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function buildMsgFor(name) {
  return "One for " + (name + ", one for me.");
}

function twoFer(name) {
  if (name !== undefined) {
    return buildMsgFor(name);
  } else {
    return "One for you, one for me.";
  }
}

exports.twoFer = twoFer;
exports.buildMsgFor = buildMsgFor;
/* No side effect */
